#
# This file contains configuration flags to customize your site
#

name: 손끝으로 만드는 세상
description: 이것저것 하는 블로그

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://inasie.github.io/images/avatar.png

# Tabs in header. There are 'Blog', 'About', 'Archive', 'Tags'
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: Home
    url: /
  - name: Tags
    url: /tags
  - name: Search
    url: /search
  # - name: Archive
  #   url: /archive
  # - name: Theme
  #   url: https://github.com/AWEEKJ/kiko-now
  # - name: About
  #   url: /about

# Pagination
paginate: 5

# Includes an icon in the footer for each username you enter
footer-links:
  behance: # https://www.behance.net/<username>
  dribbble:
  email: inasie@naver.com
  facebook:
  flickr:
  github: inasie
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter: # jekyllrb
  youtube: # channel/<your_long_string> or user/<user-name>
# Text under the icons in footer
footer-text:

disqus: # inasie-github-io # <username>.disqus.com
google_analytics: 'UA-129074475-2'

url: 'https://inasie.github.io'
baseurl: '/'

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:categories/:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
